# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
orbs: 
  win: circleci/windows@2.2.0
version: 2.1
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:        name: install_script
        command: Set-Service wuauserv -StartupType Manual
         cinst neko --version 2.3.0 -y && cinst haxe --version 4.1.5 -y && RefreshEnv && haxelib setup C:/users/circleci/haxe && haxelib install lime 7.9.0 && RefreshEnv && haxelib install openfl && haxelib install flixel && haxelib run lime setup flixel && haxelib run lime setup && haxelib install flixel-tools && haxelib install flixel-addons && haxelib install flixel-ui && haxelib install hscript && haxelib install newgrounds && haxelib install flixel-addons && haxelib git faxe https://github.com/uhrobots/faxe && haxelib git polymod https://github.com/larsiusprime/polymod.git && haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc && haxelib git extension-webm https://github.com/KadeDev/extension-webm && haxelib run lime rebuild extension-webm windows && haxelib install linc_luajit && haxelib install actuate && haxelib list
      - run:
        name: build_script
        command: haxelib run lime build windows
workflows:
  workflow:
    jobs:
      - build:
